### ISSUE TITLE
Documentation/Demo?

### ISSUE THREAD

**Issue by BrendanNeufeld** [gtg489w/Cordova-OpenEars#1]
Any chance you can provide some sample code?

**Comment by gtg489w** [comment]
I just started working on this a week ago so it's nowhere near ready. I'm also working on a sample project in tandem that can be found at https://github.com/gtg489w/Cordova-OpenEarsSample

**Comment by BrendanNeufeld** [comment]
For sure. I saw how recent you commits are. Thanks for the link. The index.js file has what I was looking for.

**Comment by gtg489w** [comment]
Updated the project with some documentation.
